// Generated by scripts/generate-agent-markdown.ts. Do not edit by hand.
// Lists the paths that have a prebuilt Markdown twin under public/md/, so the
// proxy can rewrite to the static file instead of the /md route handler.

export const MARKDOWN_BLOG_SLUGS: ReadonlySet<string> = new Set([
  "agenter-du-ikke-sitter-foran",
  "agenter-tilgang-til-sparebank-1",
  "deep-dive-deepagents",
  "eu-ai-act-for-utviklere",
  "forste-dose-er-gratis",
  "fra-solo-til-team",
  "fra-system-prompts-til-agentiske-arbeidsflyter",
  "glem-benchmarkene",
  "model-context-protocol",
  "naar-maskinene-faar-vaapen",
  "react-og-planlegging",
  "seo-i-agentenes-tidsalder",
  "sikkerhet-i-agentenes-tidsalder",
  "sisyphus-oh-my-opencode",
  "spec-driven-development",
  "testing-og-evaluering-av-agenter",
  "vibe-maxxing",
]);
