import { SiteConfig } from "@/types";

export const siteConfig: SiteConfig = {
  name: "Magnus Rødseth",
  description:
    "My personal corner of the Internet. I am Magnus Rødseth, a developer deeply committed to crafting high-quality, performant solutions.",
  url: "https://magnusrodseth.com",
  ogImage: "https://magnusrodseth.com/og.jpg",
  github: "https://github.com/magnusrodseth",
  linkedIn: "https://www.linkedin.com/in/magnus-rodseth/",
  email: "mailto:magnus.rodseth@gmail.com",
  keywords: [
    "software",
    "software engineer",
    "developer",
    "web developer",
    "full stack",
    "full stack developer",
    "full stack engineer",
    "frontend",
    "frontend developer",
    "frontend engineer",
    "backend",
    "backend developer",
    "backend engineer",
    "typescript",
    "javascript",
    "react",
    "reactjs",
    "nextjs",
    "nodejs",
    "node",
    "express",
    "graphql",
    "apollo",
    "apollo client",
    "apollo server",
    "prisma",
    "postgresql",
    "postgres",
    "supabase",
    "tailwindcss",
    "css",
    "Vercel",
    "Server-Side Rendering",
    "Static Site Generation",
    "React Framework",
    "SPA",
    "Scalable Web Applications",
    "Automatic Code Splitting",
    "Utility-First CSS Framework",
    "Custom-Built Designs",
    "Atomic CSS",
    "Responsive Design",
    "Pre-Designed UI Components",
    "PostCSS",
    "Design Systems",
    "tRPC",
    "Typesafe APIs",
    "TypeScript Inference",
    "Full-Stack TypeScript",
    "Remote Procedure Call",
    "Frontend-Backend Communication",
    "API Routes Simplification",
    "Full-Stack TypeScript Applications",
    "Modern Web Applications",
    "Prisma",
    "NextAuth.js",
    "Jamstack",
    "React Framework",
    "Database Technologies",
    "Relational Databases",
    "NoSQL Databases",
    "Graph Databases",
    "Distributed Databases",
    "DBMS",
    "SQL",
    "Data Management",
    "Technology Consulting",
    "Innovation",
    "Technical Expertise",
    "IT Services",
    "Project Management",
    "Strategy Development",
    "Client Relationship Management",
    "Solution Architecture",
    "Oslo Norway software",
    "Bergen Norway software",
    "Trondheim Norway software",
    "Stavanger Norway software",
    "NTNU",
    "Computer Science",
    "Artificial Intelligence",
    "Software Systems",
    "Interaction Design",
    "Machine Learning",
    "Data Science",
    "Human-Computer Interaction",
    "Algorithm Development",
    "Systems Engineering",
    "Robotics",
    "Natural Language Processing",
    "Computer Vision",
    "Software Development",
    "User Experience Design",
    "Computational Theory",
    "Information Systems",
    "Cybersecurity",
    "Blockchain Technology",
    "Cloud Computing",
  ],
};
