/**
 * Emits the Markdown representation of every page as a static file under
 * `public/md/`, and the route list the proxy needs to find them.
 *
 * Why static files and not just the /md route handler: Next sets its own
 * `Vary: rsc, next-router-state-tree, ...` on every App Router response,
 * replacing whatever `headers()` in next.config.mjs configured. A response
 * served straight from `public/` never reaches that code, so it keeps the
 * `Vary: Accept, Accept-Encoding` that content negotiation requires
 * (acceptmarkdown.com). The route handler stays as the 404 fallback.
 *
 * Runs from `bun run build` before `next build`.
 */
import fs from "node:fs";
import path from "node:path";
import {
  renderHome,
  renderBlogIndex,
  renderBlogPost,
  renderProjects,
  renderStaticPage,
} from "@/lib/agent-markdown";
import { getBlogSlugs } from "@/lib/blog";
import {
  ABOUT_PAGE,
  CONTACT_PAGE,
  DAILY_DRIVERS_PAGE,
  PRIVACY_PAGE,
} from "@/config/pages";

const OUT_DIR = path.join(process.cwd(), "public/md");
const ROUTES_FILE = path.join(process.cwd(), "src/lib/markdown-routes.generated.ts");

function write(relative: string, body: string): void {
  const target = path.join(OUT_DIR, relative);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, body.endsWith("\n") ? body : `${body}\n`);
}

fs.rmSync(OUT_DIR, { recursive: true, force: true });

write("index.md", renderHome());
write("blog.md", renderBlogIndex());
write("projects.md", renderProjects());

// Pages whose body is a single MDX file. Keep in step with the `markdown`
// pages in src/config/pages.ts and the /md route handler.
const staticPages = [
  [DAILY_DRIVERS_PAGE, "daily-drivers.mdx"],
  [ABOUT_PAGE, "about.mdx"],
  [CONTACT_PAGE, "contact.mdx"],
  [PRIVACY_PAGE, "privacy.mdx"],
] as const;

for (const [page, filename] of staticPages) {
  write(`${page.path.replace(/^\//, "")}.md`, renderStaticPage(page, filename));
}

const slugs = getBlogSlugs().sort();
for (const slug of slugs) {
  const body = renderBlogPost(slug);
  if (body) write(`blog/${slug}.md`, body);
}

fs.writeFileSync(
  ROUTES_FILE,
  `// Generated by scripts/generate-agent-markdown.ts. Do not edit by hand.
// Lists the paths that have a prebuilt Markdown twin under public/md/, so the
// proxy can rewrite to the static file instead of the /md route handler.

export const MARKDOWN_BLOG_SLUGS: ReadonlySet<string> = new Set([
${slugs.map((slug) => `  ${JSON.stringify(slug)},`).join("\n")}
]);
`
);

console.log(
  `Wrote ${slugs.length + 3 + staticPages.length} markdown files to public/md and ${slugs.length} slugs to markdown-routes.generated.ts`
);
